name: marketing_template_app
description: "A new Flutter project."

# Prevents accidental publication to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Additional dependencies
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  # Includes the Material Icons font
  uses-material-design: true

  # Assets section to include your images
  assets:
    - assets/images/janmastmi1.jpeg
    - assets/images/janmastmi2.jpeg
    - assets/images/janmastmi3.jpeg
    - assets/images/janmastmi4.jpeg
